name: Update Review Team

on:
  pull_request:
    types:
      - opened

jobs:
  update_review_team:
    runs-on: ubuntu-latest
    steps:
      - name: Mention @my-team
        uses: actions/github-script@v4
        with:
          script: |
            const teamName = "thezaeemaanwar"; // Update with the actual team name
            const prNumber = context.payload.pull_request.number;
            const comment = `Hey @${teamName}! There's a new pull request (#${prNumber})`;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
